import type { ShopDetails, StockInfo, Transaction } from "./types";

export const mockShopDetails: ShopDetails = {
  fpsId: "0684120",
  ownerName: "ABCD",
  location: "Vijayawada, Ward 12",
  district: "NTR",
  mandal: "Vijayawada Urban",
};

export const mockTransactions: Transaction[] = [
  {
    existingRcNumber: "2815591006",
    transStatus: "F",
    schemeShortName: "SPHH",
    schemeId: "41",
    receiptId: "332B125047805655711",
    txnId: "NIC85040761456320260505211315350ePDSAP",
    portCheck: "Self",
    amount: "17.00",
    transTime: "00.848",
    loginTime: "2026-05-05 21:13:16",
    auth_type: "Authenticated",
    commodityList: [
      {
        comm_code: 0,
        comm_name_en: "FRice",
        comm_name_ll: null,
        availed_qty: null,
        unit_type: null,
        type_ll: null,
        scheme_id: 0,
        scheme_desc: null,
        comm_scheme: null,
        source_type: null,
        comm_short: null,
        unit_type_scm: null,
        comm_id: 98,
        saleQty: null,
        allomtQty: 0.0,
        total_cards: 0,
        avail_cards: 0,
        avail_qty: null,
        availed_per: null,
        unit: null,
        qty_1: null,
        alot_month: 0,
        scheme_type: null,
        scheme_name_en: null,
        comm_measure_unit: null,
        scheme_short_name: null,
        rate: null,
        zerocount: 0,
        nonzerocount: 0,
        recqty: null,
        allocation_type: null,
        allot_qty: null,
        sale_qty: 20.0,
        nfsasaleQty: 0.0,
        statesaleQty: 0.0,
      },
      {
        comm_code: 0,
        comm_name_en: "SUGAR HALF KG",
        comm_name_ll: null,
        availed_qty: null,
        unit_type: null,
        type_ll: null,
        scheme_id: 0,
        scheme_desc: null,
        comm_scheme: null,
        source_type: null,
        comm_short: null,
        unit_type_scm: null,
        comm_id: 312,
        saleQty: null,
        allomtQty: 0.0,
        total_cards: 0,
        avail_cards: 0,
        avail_qty: null,
        availed_per: null,
        unit: null,
        qty_1: null,
        alot_month: 0,
        scheme_type: null,
        scheme_name_en: null,
        comm_measure_unit: null,
        scheme_short_name: null,
        rate: null,
        zerocount: 0,
        nonzerocount: 0,
        recqty: null,
        allocation_type: null,
        allot_qty: null,
        sale_qty: 1.0,
        nfsasaleQty: 0.0,
        statesaleQty: 0.0,
      },
      {
        comm_code: 0,
        comm_name_en: "WM Atta Pkt",
        comm_name_ll: null,
        availed_qty: null,
        unit_type: null,
        type_ll: null,
        scheme_id: 0,
        scheme_desc: null,
        comm_scheme: null,
        source_type: null,
        comm_short: null,
        unit_type_scm: null,
        comm_id: 701,
        saleQty: null,
        allomtQty: 0.0,
        total_cards: 0,
        avail_cards: 0,
        avail_qty: null,
        availed_per: null,
        unit: null,
        qty_1: null,
        alot_month: 0,
        scheme_type: null,
        scheme_name_en: null,
        comm_measure_unit: null,
        scheme_short_name: null,
        rate: null,
        zerocount: 0,
        nonzerocount: 0,
        recqty: null,
        allocation_type: null,
        allot_qty: null,
        sale_qty: 0.0,
        nfsasaleQty: 0.0,
        statesaleQty: 0.0,
      },
    ],
  },
  {
    existingRcNumber: "2813794302",
    transStatus: "F",
    schemeShortName: "SPHH",
    schemeId: "41",
    receiptId: "332B125517457146663",
    txnId: "UKC:NIC26015476867420260505194722874ePDSAP",
    portCheck: "0107001",
    amount: "17.00",
    transTime: "00.845",
    loginTime: "2026-05-05 19:47:23",
    auth_type: "Authenticated",
    commodityList: [
      {
        comm_code: 0,
        comm_name_en: "FRice",
        comm_name_ll: null,
        availed_qty: null,
        unit_type: null,
        type_ll: null,
        scheme_id: 0,
        scheme_desc: null,
        comm_scheme: null,
        source_type: null,
        comm_short: null,
        unit_type_scm: null,
        comm_id: 98,
        saleQty: null,
        allomtQty: 0.0,
        total_cards: 0,
        avail_cards: 0,
        avail_qty: null,
        availed_per: null,
        unit: null,
        qty_1: null,
        alot_month: 0,
        scheme_type: null,
        scheme_name_en: null,
        comm_measure_unit: null,
        scheme_short_name: null,
        rate: null,
        zerocount: 0,
        nonzerocount: 0,
        recqty: null,
        allocation_type: null,
        allot_qty: null,
        sale_qty: 20.0,
        nfsasaleQty: 0.0,
        statesaleQty: 0.0,
      },
      {
        comm_code: 0,
        comm_name_en: "SUGAR HALF KG",
        comm_name_ll: null,
        availed_qty: null,
        unit_type: null,
        type_ll: null,
        scheme_id: 0,
        scheme_desc: null,
        comm_scheme: null,
        source_type: null,
        comm_short: null,
        unit_type_scm: null,
        comm_id: 312,
        saleQty: null,
        allomtQty: 0.0,
        total_cards: 0,
        avail_cards: 0,
        avail_qty: null,
        availed_per: null,
        unit: null,
        qty_1: null,
        alot_month: 0,
        scheme_type: null,
        scheme_name_en: null,
        comm_measure_unit: null,
        scheme_short_name: null,
        rate: null,
        zerocount: 0,
        nonzerocount: 0,
        recqty: null,
        allocation_type: null,
        allot_qty: null,
        sale_qty: 1.0,
        nfsasaleQty: 0.0,
        statesaleQty: 0.0,
      },
      {
        comm_code: 0,
        comm_name_en: "WM Atta Pkt",
        comm_name_ll: null,
        availed_qty: null,
        unit_type: null,
        type_ll: null,
        scheme_id: 0,
        scheme_desc: null,
        comm_scheme: null,
        source_type: null,
        comm_short: null,
        unit_type_scm: null,
        comm_id: 701,
        saleQty: null,
        allomtQty: 0.0,
        total_cards: 0,
        avail_cards: 0,
        avail_qty: null,
        availed_per: null,
        unit: null,
        qty_1: null,
        alot_month: 0,
        scheme_type: null,
        scheme_name_en: null,
        comm_measure_unit: null,
        scheme_short_name: null,
        rate: null,
        zerocount: 0,
        nonzerocount: 0,
        recqty: null,
        allocation_type: null,
        allot_qty: null,
        sale_qty: 0.0,
        nfsasaleQty: 0.0,
        statesaleQty: 0.0,
      },
    ],
  },
];

export const mockStock: StockInfo[] = [
  {
    commodity: "Rice",
    openingBalance: 1250.5,
    receipts: 2000.0,
    totalStock: 3250.5,
    sales: 1840.0,
    closingBalance: 1410.5,
  },
  {
    commodity: "Sugar",
    openingBalance: 45.2,
    receipts: 100.0,
    totalStock: 145.2,
    sales: 92.5,
    closingBalance: 52.7,
  },
];
